name: Publish to Maven Central

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional, uses gradle.properties if not specified)'
        required: false
        type: string

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

permissions:
  contents: write

jobs:
  publish:
    environment:
      name: maven-central
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Run tests before publishing
        run: ./gradlew build --stacktrace

      - name: Set version from tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set version for manual dispatch
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
        run: |
          echo "VERSION_NAME=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Publish to Maven Central
        uses: nick-fields/retry@v2
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 20
          command: ./gradlew :code-path-tracer:publish --rerun-tasks --stacktrace --no-configuration-cache -PVERSION_NAME=${VERSION_NAME:-}

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            This release includes the latest improvements to Code Path Tracer.
            
            ### Installation
            
            Add to your `build.gradle`:
            ```kotlin
            dependencies {
                testImplementation("io.github.takahirom.codepathtracer:code-path-tracer:${{ github.ref_name }}")
            }
            ```
            
            Full Changelog: https://github.com/takahirom/code-path-tracer/commits/${{ github.ref_name }}
          draft: false
          prerelease: false